spring:
  application:
    name: RTDS
  config:
    import:
      - optional:configserver:http://localhost:8888

server:
  port: 8081

logging:
  level:
    root: ERROR

eureka:
  client:
    enabled: false
