spring:
  application:
    name: JDRS
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8082

logging:
  level:
    root: ERROR


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

